name: 编译 iOS 测试包
on:
  push:
    branches: [ main ]  # 推送到 main 分支时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: macos-latest  # 使用 macOS 虚拟机
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'

      - name: 检查Flutter环境
        run: |
          flutter --version
          flutter doctor
          
      - name: 安装依赖
        run: |
          flutter pub get
          flutter pub deps

      - name: 编译 IPA（未签名，仅测试用）
        run: |
          flutter clean
          flutter pub get
          cd ios 
          rm -rf Pods
          rm -rf .symlinks
          rm -f Podfile.lock
          pod cache clean --all
          pod install
          cd ..
          flutter build ios --release --no-codesign --no-tree-shake-icons

      - name: 打包 IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -R Runner.app Payload/
          zip -r ../../../Runner.ipa Payload/

      - name: 保存 IPA 包
        uses: actions/upload-artifact@v4
        with:
          name: my-ios-app
          path: Runner.ipa
